allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir("../../build").get())

subprojects {
    project.layout.buildDirectory.value(rootProject.layout.buildDirectory.dir(project.name).get())
}

// Función para inyectar namespace a plugins antiguos
def fixNamespace(prj) {
    if (prj.hasProperty("android")) {
        if (prj.android.namespace == null) {
            def manifestFile = prj.file("src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifest = new XmlParser().parse(manifestFile)
                def packageName = manifest."@package"
                if (packageName != null) {
                    prj.android.namespace = packageName
                }
            }
        }
    }
}

// Aplicar la corrección a todos los subproyectos
subprojects {
    if (project.state.executed) {
        fixNamespace(project)
    } else {
        project.afterEvaluate {
            fixNamespace(project)
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
