allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    // Parche de Namespace para plugins antiguos
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            if (project.android.namespace == null) {
                def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
                if (manifestFile.exists()) {
                    def manifestXml = new XmlParser().parse(manifestFile)
                    def packageName = manifestXml.@package
                    if (packageName) {
                        project.android.namespace = packageName
                    } else {
                        project.android.namespace = "co.edu.unbosque.stem_bosque.plugin.${project.name.replaceAll(/[^a-zA-Z0-9]/, "")}"
                    }
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
