org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Desactivar validaciones de AGP 9+ que rompen Flutter
android.experimental.privacysandboxsdk.enable=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# Forzar que Flutter no valide el ciclo de vida de forma estricta
flutter.disable-lifecycle-check=true
