org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Opt-out of AGP 9+ new DSL validation
android.experimental.privacysandboxsdk.enable=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This is the magic flag to stop Flutter from crashing on Gradle evaluation
flutter.disable-lifecycle-check=true
android.newDsl=false
